common: &common
  adapter: postgresql
  username: hype2010
  password: ohdohwutho
  host: localhost

development:
  <<: *common
  database: hype2010-final

test:
  <<: *common
  database: hype2010-final

production:
  <<: *common
  database: hype2010-final
